plugins = []
functionsDirectory = ".netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
  publish = "dist"
  publishOrigin = "ui"
  command = "npm run build"
  commandOrigin = "ui"
  functions = ".netlify/functions"

[build.environment]
  NODE_ENV = "production"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.js]
  bundle = true
  minify = true

[build.services]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]